"""phase2_masters_territories_customers

Revision ID: 7790c3bd304b
Revises: 411b81995e29
Create Date: 2026-10-01 23:28:29.232170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7790c3bd304b'
down_revision: Union[str, Sequence[str], None] = '411b81995e29'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_items',
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('type', 'code', name='uq_master_items_type_code')
    )
    op.create_index(op.f('ix_master_items_client_uuid'), 'master_items', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_master_items_code'), 'master_items', ['code'], unique=False)
    op.create_index(op.f('ix_master_items_type'), 'master_items', ['type'], unique=False)
    op.create_table('states',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_states_client_uuid'), 'states', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_states_code'), 'states', ['code'], unique=True)
    op.create_index(op.f('ix_states_name'), 'states', ['name'], unique=True)
    op.create_table('cities',
    sa.Column('state_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cities_client_uuid'), 'cities', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_cities_name'), 'cities', ['name'], unique=False)
    op.create_index(op.f('ix_cities_state_id'), 'cities', ['state_id'], unique=False)
    op.create_table('territories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('headquarters', sa.String(length=100), nullable=False),
    sa.Column('state_id', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['state_id'], ['states.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territories_client_uuid'), 'territories', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_territories_code'), 'territories', ['code'], unique=True)
    op.create_index(op.f('ix_territories_name'), 'territories', ['name'], unique=False)
    op.create_index(op.f('ix_territories_state_id'), 'territories', ['state_id'], unique=False)
    op.create_table('areas',
    sa.Column('city_id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_areas_city_id'), 'areas', ['city_id'], unique=False)
    op.create_index(op.f('ix_areas_client_uuid'), 'areas', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_areas_name'), 'areas', ['name'], unique=False)
    op.create_index(op.f('ix_areas_pincode'), 'areas', ['pincode'], unique=False)
    op.create_table('user_territory_assignments',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('territory_id', sa.BigInteger(), nullable=False),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('unassigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_territory_assignments_client_uuid'), 'user_territory_assignments', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_user_territory_assignments_territory_id'), 'user_territory_assignments', ['territory_id'], unique=False)
    op.create_index(op.f('ix_user_territory_assignments_user_id'), 'user_territory_assignments', ['user_id'], unique=False)
    op.create_table('chemists',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('shop_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('dl_number', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.BigInteger(), nullable=True),
    sa.Column('territory_id', sa.BigInteger(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chemists_area_id'), 'chemists', ['area_id'], unique=False)
    op.create_index(op.f('ix_chemists_client_uuid'), 'chemists', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_chemists_code'), 'chemists', ['code'], unique=True)
    op.create_index(op.f('ix_chemists_shop_name'), 'chemists', ['shop_name'], unique=False)
    op.create_index(op.f('ix_chemists_territory_id'), 'chemists', ['territory_id'], unique=False)
    op.create_table('doctors',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=False),
    sa.Column('qualification', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('clinic_name', sa.String(length=150), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.BigInteger(), nullable=True),
    sa.Column('territory_id', sa.BigInteger(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('anniversary_date', sa.Date(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_doctors_area_id'), 'doctors', ['area_id'], unique=False)
    op.create_index(op.f('ix_doctors_category'), 'doctors', ['category'], unique=False)
    op.create_index(op.f('ix_doctors_client_uuid'), 'doctors', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_doctors_code'), 'doctors', ['code'], unique=True)
    op.create_index(op.f('ix_doctors_full_name'), 'doctors', ['full_name'], unique=False)
    op.create_index(op.f('ix_doctors_specialization'), 'doctors', ['specialization'], unique=False)
    op.create_index(op.f('ix_doctors_territory_id'), 'doctors', ['territory_id'], unique=False)
    op.create_table('hospitals',
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.BigInteger(), nullable=True),
    sa.Column('territory_id', sa.BigInteger(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('bed_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hospitals_area_id'), 'hospitals', ['area_id'], unique=False)
    op.create_index(op.f('ix_hospitals_client_uuid'), 'hospitals', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_hospitals_code'), 'hospitals', ['code'], unique=True)
    op.create_index(op.f('ix_hospitals_name'), 'hospitals', ['name'], unique=False)
    op.create_index(op.f('ix_hospitals_territory_id'), 'hospitals', ['territory_id'], unique=False)
    op.create_table('stockists',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('agency_name', sa.String(length=150), nullable=False),
    sa.Column('contact_person', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=25), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('dl_number', sa.String(length=100), nullable=True),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('area_id', sa.BigInteger(), nullable=True),
    sa.Column('territory_id', sa.BigInteger(), nullable=True),
    sa.Column('pincode', sa.String(length=10), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('credit_days', sa.Integer(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stockists_agency_name'), 'stockists', ['agency_name'], unique=False)
    op.create_index(op.f('ix_stockists_area_id'), 'stockists', ['area_id'], unique=False)
    op.create_index(op.f('ix_stockists_client_uuid'), 'stockists', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_stockists_code'), 'stockists', ['code'], unique=True)
    op.create_index(op.f('ix_stockists_territory_id'), 'stockists', ['territory_id'], unique=False)
    op.create_table('territory_areas',
    sa.Column('territory_id', sa.BigInteger(), nullable=False),
    sa.Column('area_id', sa.BigInteger(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['territory_id'], ['territories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_territory_areas_area_id'), 'territory_areas', ['area_id'], unique=False)
    op.create_index(op.f('ix_territory_areas_client_uuid'), 'territory_areas', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_territory_areas_territory_id'), 'territory_areas', ['territory_id'], unique=False)
    op.create_table('hospital_doctors',
    sa.Column('hospital_id', sa.BigInteger(), nullable=False),
    sa.Column('doctor_id', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('visiting_hours', sa.String(length=100), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('client_uuid', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('updated_by', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['doctor_id'], ['doctors.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['hospital_id'], ['hospitals.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('hospital_id', 'doctor_id', name='uq_hospital_doctor')
    )
    op.create_index(op.f('ix_hospital_doctors_client_uuid'), 'hospital_doctors', ['client_uuid'], unique=True)
    op.create_index(op.f('ix_hospital_doctors_doctor_id'), 'hospital_doctors', ['doctor_id'], unique=False)
    op.create_index(op.f('ix_hospital_doctors_hospital_id'), 'hospital_doctors', ['hospital_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_hospital_doctors_hospital_id'), table_name='hospital_doctors')
    op.drop_index(op.f('ix_hospital_doctors_doctor_id'), table_name='hospital_doctors')
    op.drop_index(op.f('ix_hospital_doctors_client_uuid'), table_name='hospital_doctors')
    op.drop_table('hospital_doctors')
    op.drop_index(op.f('ix_territory_areas_territory_id'), table_name='territory_areas')
    op.drop_index(op.f('ix_territory_areas_client_uuid'), table_name='territory_areas')
    op.drop_index(op.f('ix_territory_areas_area_id'), table_name='territory_areas')
    op.drop_table('territory_areas')
    op.drop_index(op.f('ix_stockists_territory_id'), table_name='stockists')
    op.drop_index(op.f('ix_stockists_code'), table_name='stockists')
    op.drop_index(op.f('ix_stockists_client_uuid'), table_name='stockists')
    op.drop_index(op.f('ix_stockists_area_id'), table_name='stockists')
    op.drop_index(op.f('ix_stockists_agency_name'), table_name='stockists')
    op.drop_table('stockists')
    op.drop_index(op.f('ix_hospitals_territory_id'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_name'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_code'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_client_uuid'), table_name='hospitals')
    op.drop_index(op.f('ix_hospitals_area_id'), table_name='hospitals')
    op.drop_table('hospitals')
    op.drop_index(op.f('ix_doctors_territory_id'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_specialization'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_full_name'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_code'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_client_uuid'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_category'), table_name='doctors')
    op.drop_index(op.f('ix_doctors_area_id'), table_name='doctors')
    op.drop_table('doctors')
    op.drop_index(op.f('ix_chemists_territory_id'), table_name='chemists')
    op.drop_index(op.f('ix_chemists_shop_name'), table_name='chemists')
    op.drop_index(op.f('ix_chemists_code'), table_name='chemists')
    op.drop_index(op.f('ix_chemists_client_uuid'), table_name='chemists')
    op.drop_index(op.f('ix_chemists_area_id'), table_name='chemists')
    op.drop_table('chemists')
    op.drop_index(op.f('ix_user_territory_assignments_user_id'), table_name='user_territory_assignments')
    op.drop_index(op.f('ix_user_territory_assignments_territory_id'), table_name='user_territory_assignments')
    op.drop_index(op.f('ix_user_territory_assignments_client_uuid'), table_name='user_territory_assignments')
    op.drop_table('user_territory_assignments')
    op.drop_index(op.f('ix_areas_pincode'), table_name='areas')
    op.drop_index(op.f('ix_areas_name'), table_name='areas')
    op.drop_index(op.f('ix_areas_client_uuid'), table_name='areas')
    op.drop_index(op.f('ix_areas_city_id'), table_name='areas')
    op.drop_table('areas')
    op.drop_index(op.f('ix_territories_state_id'), table_name='territories')
    op.drop_index(op.f('ix_territories_name'), table_name='territories')
    op.drop_index(op.f('ix_territories_code'), table_name='territories')
    op.drop_index(op.f('ix_territories_client_uuid'), table_name='territories')
    op.drop_table('territories')
    op.drop_index(op.f('ix_cities_state_id'), table_name='cities')
    op.drop_index(op.f('ix_cities_name'), table_name='cities')
    op.drop_index(op.f('ix_cities_client_uuid'), table_name='cities')
    op.drop_table('cities')
    op.drop_index(op.f('ix_states_name'), table_name='states')
    op.drop_index(op.f('ix_states_code'), table_name='states')
    op.drop_index(op.f('ix_states_client_uuid'), table_name='states')
    op.drop_table('states')
    op.drop_index(op.f('ix_master_items_type'), table_name='master_items')
    op.drop_index(op.f('ix_master_items_code'), table_name='master_items')
    op.drop_index(op.f('ix_master_items_client_uuid'), table_name='master_items')
    op.drop_table('master_items')
    # ### end Alembic commands ###
