"""Authentication and security constants."""

MAX_FAILED_LOGIN_ATTEMPTS: int = 5
LOCKOUT_DURATION_MINUTES: int = 15

# Audit Log Action Names
AUTH_LOGIN_SUCCESS: str = "AUTH_LOGIN_SUCCESS"
AUTH_LOGIN_FAILED: str = "AUTH_LOGIN_FAILED"
AUTH_LOCKOUT: str = "AUTH_LOCKOUT"
AUTH_LOGOUT: str = "AUTH_LOGOUT"
AUTH_LOGOUT_ALL: str = "AUTH_LOGOUT_ALL"
AUTH_TOKEN_REFRESH: str = "AUTH_TOKEN_REFRESH"
AUTH_TOKEN_REUSE_DETECTED: str = "AUTH_TOKEN_REUSE_DETECTED"
AUTH_PASSWORD_CHANGED: str = "AUTH_PASSWORD_CHANGED"
AUTH_REGISTER: str = "AUTH_REGISTER"
