"""Excel generation engine using openpyxl conforming to Section 7 of Reports Spec."""

from __future__ import annotations

import io
from typing import Any

import openpyxl
from openpyxl.styles import Alignment, Border, Font, PatternFill, Side
from openpyxl.utils import get_column_letter

from app.modules.reports.schemas import ReportColumn, ReportMeta


class ReportExcelGenerator:
    """Builds multi-sheet enterprise Excel workbooks matching Section 7 specifications."""

    DEEP_GREEN_HEX = "0C5D46"
    SOFT_GREEN_HEX = "DCFCE7"
    LIGHT_BG_HEX = "F3F7FA"
    BORDER_HEX = "EDEEF6"

    def __init__(self, meta: ReportMeta, columns: list[ReportColumn]) -> None:
        self.meta = meta
        self.columns = columns

        # Styles
        self.header_fill = PatternFill(
            start_color=self.DEEP_GREEN_HEX,
            end_color=self.DEEP_GREEN_HEX,
            fill_type="solid",
        )
        self.header_font = Font(name="Calibri", size=11, bold=True, color="FFFFFF")
        self.subtotal_fill = PatternFill(
            start_color=self.SOFT_GREEN_HEX,
            end_color=self.SOFT_GREEN_HEX,
            fill_type="solid",
        )
        self.subtotal_font = Font(name="Calibri", size=10, bold=True, color="0C5D46")
        self.thin_border = Border(
            left=Side(style="thin", color="CCCCCC"),
            right=Side(style="thin", color="CCCCCC"),
            top=Side(style="thin", color="CCCCCC"),
            bottom=Side(style="thin", color="CCCCCC"),
        )

    def generate(self, items: list[dict[str, Any]], summary: dict[str, Any]) -> bytes:
        """Render report into Excel workbook bytes."""
        wb = openpyxl.Workbook()
        # 1. Summary Sheet
        ws_summary = wb.active
        ws_summary.title = "Summary"
        self._populate_summary_sheet(ws_summary, summary)

        # 2. Data Sheet
        ws_data = wb.create_sheet(title="Data")
        self._populate_data_sheet(ws_data, items)

        # 3. Optional "By Date" Sheet for R01
        if self.meta.key == "dcr_detailed" and items:
            ws_by_date = wb.create_sheet(title="By Date")
            self._populate_by_date_sheet(ws_by_date, items)

        buffer = io.BytesIO()
        wb.save(buffer)
        return buffer.getvalue()

    def _populate_summary_sheet(self, ws: Any, summary: dict[str, Any]) -> None:
        ws.views.sheetView[0].showGridLines = True

        # Company & Report Title
        ws["A1"] = "Mediate Healthcare - Field Operations"
        ws["A1"].font = Font(name="Calibri", size=16, bold=True, color=self.DEEP_GREEN_HEX)

        ws["A2"] = self.meta.title
        ws["A2"].font = Font(name="Calibri", size=13, bold=True, color="0F172A")

        ws["A3"] = f"Report Group: {self.meta.group}"
        ws["A3"].font = Font(name="Calibri", size=10, italic=True, color="64748B")

        # Report Metadata Block
        ws["A5"] = "Report Filter Parameters"
        ws["A5"].font = Font(name="Calibri", size=11, bold=True)
        ws["A5"].fill = self.subtotal_fill

        filters_info = [
            (
                "Reporting Range",
                f"{self.meta.filters.get('from_date', '-')} to {self.meta.filters.get('to_date', '-')}",
            ),
            ("Scope", self.meta.scope_label or "All"),
            ("Generated By", self.meta.filters.get("generated_by", "Authorized User")),
            ("Generated At (IST)", self.meta.generated_at),
        ]

        row_idx = 6
        for lbl, val in filters_info:
            ws.cell(row=row_idx, column=1, value=lbl).font = Font(bold=True)
            ws.cell(row=row_idx, column=2, value=val)
            row_idx += 1

        # Key Performance Indicators Table
        row_idx += 1
        ws.cell(
            row=row_idx, column=1, value="Operational Summary & Key Performance Indicators"
        ).font = Font(bold=True)
        ws.cell(row=row_idx, column=1).fill = self.subtotal_fill
        ws.cell(row=row_idx, column=2, value="Metric Value").font = Font(bold=True)
        ws.cell(row=row_idx, column=2).fill = self.subtotal_fill

        row_idx += 1
        for k, v in summary.items():
            lbl = k.replace("_", " ").title()
            ws.cell(row=row_idx, column=1, value=lbl).border = self.thin_border
            val_cell = ws.cell(row=row_idx, column=2, value=v)
            val_cell.border = self.thin_border
            val_cell.alignment = Alignment(horizontal="right")
            if "amount" in k or "claimed" in k:
                val_cell.number_format = "#,##0.00"
            elif "pct" in k:
                val_cell.number_format = "0.0%"
            elif isinstance(v, (int, float)):
                val_cell.number_format = "#,##0"
            row_idx += 1

        ws.column_dimensions["A"].width = 32
        ws.column_dimensions["B"].width = 30

    def _populate_data_sheet(self, ws: Any, items: list[dict[str, Any]]) -> None:
        ws.views.sheetView[0].showGridLines = True
        if self.meta.key in ["mr_wise_attendance_report"]:
            ws.freeze_panes = "B2"
        else:
            ws.freeze_panes = "A2"

        if getattr(self.meta, "landscape", False):
            ws.page_setup.orientation = ws.ORIENTATION_LANDSCAPE

        # Header Row
        for col_idx, col in enumerate(self.columns, start=1):
            cell = ws.cell(row=1, column=col_idx, value=col.label)
            cell.fill = self.header_fill
            cell.font = self.header_font
            cell.alignment = Alignment(
                horizontal="center"
                if col.align == "center"
                else ("right" if col.align == "right" else "left")
            )
            cell.border = self.thin_border

        if not items:
            ws.cell(row=2, column=1, value="No records for the selected filters.")
            return

        # Data Rows
        numeric_col_indices: list[int] = []
        for row_idx, item in enumerate(items, start=2):
            for col_idx, col in enumerate(self.columns, start=1):
                raw_val = item.get(col.key)
                cell = ws.cell(row=row_idx, column=col_idx)
                cell.border = self.thin_border

                if col.align == "right":
                    cell.alignment = Alignment(horizontal="right")
                elif col.align == "center":
                    cell.alignment = Alignment(horizontal="center")
                else:
                    cell.alignment = Alignment(
                        horizontal="left",
                        wrap_text=(col.key in ["remarks", "description", "reason"]),
                    )

                # Type formatting
                if col.type == "number" and isinstance(raw_val, (int, float)):
                    cell.value = raw_val
                    cell.number_format = "#,##0" if isinstance(raw_val, int) else "#,##0.0"
                    if col_idx not in numeric_col_indices:
                        numeric_col_indices.append(col_idx)
                elif col.type == "currency" and isinstance(raw_val, (int, float)):
                    cell.value = float(raw_val)
                    cell.number_format = "#,##0.00"
                    if col_idx not in numeric_col_indices:
                        numeric_col_indices.append(col_idx)
                elif col.type == "percent" and isinstance(raw_val, str) and raw_val.endswith("%"):
                    try:
                        num = float(raw_val.replace("%", "")) / 100.0
                        cell.value = num
                        cell.number_format = "0.0%"
                    except ValueError:
                        cell.value = raw_val
                else:
                    cell.value = str(raw_val) if raw_val is not None else "-"

        total_row_idx = len(items) + 2

        # Totals row with SUM formulas
        if numeric_col_indices and len(items) > 0:
            ws.cell(row=total_row_idx, column=1, value="Total / Summary").font = self.subtotal_font
            ws.cell(row=total_row_idx, column=1).fill = self.subtotal_fill

            for col_idx in range(1, len(self.columns) + 1):
                cell = ws.cell(row=total_row_idx, column=col_idx)
                cell.fill = self.subtotal_fill
                cell.border = self.thin_border
                col_letter = get_column_letter(col_idx)
                if col_idx in numeric_col_indices:
                    cell.value = f"=SUM({col_letter}2:{col_letter}{total_row_idx - 1})"
                    cell.font = self.subtotal_font
                    cell.alignment = Alignment(horizontal="right")

        # Auto-filter
        ws.auto_filter.ref = f"A1:{get_column_letter(len(self.columns))}{len(items) + 1}"

        # Adjust column widths
        for col_idx, col in enumerate(self.columns, start=1):
            letter = get_column_letter(col_idx)
            max_len = max(len(col.label), 10)
            if col.key in ["remarks", "products_promoted", "places", "description", "reason"]:
                ws.column_dimensions[letter].width = 30
            else:
                ws.column_dimensions[letter].width = min(max_len + 4, 25)

    def _populate_by_date_sheet(self, ws: Any, items: list[dict[str, Any]]) -> None:
        """R01 DCR Detailed: Daily Subtotals breakdown sheet."""
        ws.views.sheetView[0].showGridLines = True
        ws.freeze_panes = "A2"

        headers = [
            "Date",
            "Total Calls",
            "Doctors",
            "Chemists",
            "Stockists",
            "Hospitals",
            "Verified Calls",
            "Verified %",
        ]
        for col_idx, h in enumerate(headers, start=1):
            c = ws.cell(row=1, column=col_idx, value=h)
            c.fill = self.header_fill
            c.font = self.header_font
            c.border = self.thin_border
            c.alignment = Alignment(horizontal="center")

        grouped: dict[str, list[dict[str, Any]]] = {}
        for it in items:
            d = it.get("date", "Unknown")
            grouped.setdefault(d, []).append(it)

        for row_idx, (d, d_items) in enumerate(grouped.items(), start=2):
            tot = len(d_items)
            docs = sum(
                1 for x in d_items if str(x.get("_raw_customer_type", "")).upper() == "DOCTOR"
            )
            chem = sum(
                1 for x in d_items if str(x.get("_raw_customer_type", "")).upper() == "CHEMIST"
            )
            stock = sum(
                1 for x in d_items if str(x.get("_raw_customer_type", "")).upper() == "STOCKIST"
            )
            hosp = sum(
                1 for x in d_items if str(x.get("_raw_customer_type", "")).upper() == "HOSPITAL"
            )
            ver = sum(1 for x in d_items if x.get("_raw_verified"))
            pct = round(ver / tot, 3) if tot > 0 else 0.0

            vals = [d, tot, docs, chem, stock, hosp, ver, pct]
            for col_idx, v in enumerate(vals, start=1):
                cell = ws.cell(row=row_idx, column=col_idx, value=v)
                cell.border = self.thin_border
                if col_idx == 1:
                    cell.alignment = Alignment(horizontal="center")
                elif col_idx == 8:
                    cell.number_format = "0.0%"
                    cell.alignment = Alignment(horizontal="right")
                else:
                    cell.number_format = "#,##0"
                    cell.alignment = Alignment(horizontal="right")

        for col_idx in range(1, 9):
            ws.column_dimensions[get_column_letter(col_idx)].width = 16
